name: Deploy Frontend to S3
on:
  push:
    branches:
      - team4-prachi # Trigger on pushes to the main branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      - name: Build Frontend
        run: npm run build # Or your specific build command
        working-directory: ./frontend
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # e.g., us-east-1
      - name: Upload to S3
        run: aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET }} --delete # Adjust 'build' to your build output directory
        working-directory: ./frontend
      - name: Invalidate CloudFront Cache (Optional)
        if: success() # Only run if S3 upload is successful
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.YOUR_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"